# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'VKapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKapp
  pod 'Alamofire', '= 4.8.2'
  pod 'SwiftyJSON', '= 5.0.0'
  pod 'Kingfisher', '= 5.7.1'
  pod 'RealmSwift', '= 3.17.3'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
